# Generated by Django 5.1.4 on 2024-12-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciCli', models.PositiveBigIntegerField()),
                ('nombreCli', models.CharField(max_length=50)),
                ('apellidoPaternoCli', models.CharField(max_length=50)),
                ('emailCli', models.EmailField(max_length=30)),
                ('passwordCli', models.CharField(max_length=30)),
            ],
        ),
    ]
