# Generated by Django 5.1.4 on 2024-12-08 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAPP', '0001_initial'),
    ]

    operations = [
    ]
