# Generated by Django 5.1.4 on 2024-12-08 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientesAPP', '0002_auto_20241207_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientes',
        ),
    ]
